### ISSUE TITLE
Fatal error: Uncaught PHPStamp\Exception\ProcessorException: Unexpected token

### ISSUE THREAD

**Issue by biswajitpaul01** [shadz3rg/PHPStamp#11]
Hi,

I am getting this issue on my localhost.

Error URL: https://imgur.com/a/OqLxMhO

Doc & PHP Template : https://filebin.net/tc76riowvwbzgrq5

**Comment by shadz3rg** [comment]
Outdated.

**Comment by biswajitpaul01** [comment]
That's a nice trick.
