### ISSUE TITLE
Unexpected token in Lexer

### ISSUE THREAD

**Issue by reimax** [shadz3rg/PHPStamp#13]
i have document:

[[current_date]]
text text 
[[number_test]]
text text 
[[пример_тест]]

save in format office open xml (docx) in libre office in .docx ext.
and get error:

Unexpected token, expected PHPStamp\Processor\Lexer::T_DOT, got PHPStamp\Processor\Lexer::T_STRING

how to fix?

**Comment by shadz3rg** [comment]
Cyrillic placeholders are not expected or supported.
