### ISSUE TITLE
Не заполняются дублирующие таблицы

### ISSUE THREAD

**Issue by katarsies** [shadz3rg/PHPStamp#14]
Добрый день! Возникла ситуация когда в одном документе должно быть 2 таблицы с одинаковыми данными, но при генерации почему-то заполняется только одна таблица. 

**Шаблон:**
![Аннотация 2019-05-08 162933](https://user-images.githubusercontent.com/21752309/57372284-989a2d80-71ae-11e9-933a-8e5329db65a7.png)

**Что из него получилось:**
![Аннотация 2019-05-08 163209](https://user-images.githubusercontent.com/21752309/57372352-d72fe800-71ae-11e9-88c0-f522e9d523c0.png)

**Comment by shadz3rg** [comment]
Добавил аргумент для явного указания имени шаблона.
Use-case: [[id:cell(students,students_1)]]
