### ISSUE TITLE
May be publish first 0.1.0 release?

### ISSUE THREAD

**Issue by roquie** [shadz3rg/PHPStamp#2]
I would like use library without `minimum-stability dev`. Now, it has been more than 3 years, and it's time that for version.
___

Давно пора, даже если это прототип :) Композер будет намного удобнее использовать.

**Comment by shadz3rg** [comment]
Применил, должно работать. Спасибо!)

**Comment by roquie** [comment]
О, спасибо. Работает!

**Comment by roquie** [comment]
@shadz3rg Олег, мне прислали вакансию для вас 😄  Я не знаю вашей почты, куда вам перекинуть переписку?

**Comment by shadz3rg** [comment]
@roquie, Работу я пока не ищу, но спасибо за предложение!)
Извиняюсь, не заметил ваше сообщение раньше)

**Comment by roquie** [comment]
Да не страшно :) просто забавная ситуация.
