### ISSUE TITLE
Не работают списки на никс серверах

### ISSUE THREAD

**Issue by ijusss** [shadz3rg/PHPStamp#5]
Мне разработчик сказал, что "в самом коде также есть со списками небольшая ошибка(будет работать на вин, но не на никс хостинге)". Так и случилось: списки перестали работать когда закинул с локального сервера на хостинг (OS Ubuntu (Linux)). Прошу ответить, что можно сделать, чтобы генерировались списки в шаблоне в том числе на никс серверах?

**Comment by shadz3rg** [comment]
Спасибо за сообщение!) 
Был баг с регистром класса, сейчас должно работать как следует.

**Comment by ijusss** [comment]
А сейчас надо заново скачать phpstamp?

**Comment by shadz3rg** [comment]
@ijusss да, или можно обновить через `composer update shadz3rg/php-stamp`
версия должна быть 0.1.2

**Comment by ijusss** [comment]
Ок, сделано ) пользуюсь твоим скриптом в своей системе управления проектами) 
Подскажи, а имя выдаваемого файла можно менять? Или только возможно брать имя шаблона?

**Comment by shadz3rg** [comment]
@ijusss имя файла можно задать при вызове метода download
https://github.com/shadz3rg/PHPStamp/blob/master/src/PHPStamp/Result.php#L24

**Comment by ijusss** [comment]
Спасибо, сделал
