### ISSUE TITLE
PHPStamp deletes the table

### ISSUE THREAD

**Issue by tventos** [shadz3rg/PHPStamp#7]
When I try to insert information into a table, PHPStamp deletes the table and inserts just information
in $values
`'services' => [
     ['service' => $model->provided_services_1, 'price'=>$model->provided_services_1_price]
]`

in template
![default](https://user-images.githubusercontent.com/11913644/33070683-adb25936-ceda-11e7-8eb8-ab0aa968af3e.PNG)

ouput
![1](https://user-images.githubusercontent.com/11913644/33070685-adf09c96-ceda-11e7-9616-8e16dda2db57.PNG)

What could be the problem? Thanks!

**Comment by duxabilii** [comment]
It could be an empty array passed to services

**Comment by tventos** [comment]
The array is not empty, because it passes information to the template, deleting the table..

**Comment by shadz3rg** [comment]
Если у кого повторится этот баг - переоткройте эту тему и пришлите пример файла.
