### ISSUE TITLE
Как отключить принудительное кеширование используемого шаблона?

### ISSUE THREAD

**Issue by vkatochka** [shadz3rg/PHPStamp#9]
Как отключить принудительное кеширование используемого шаблона? Есть ли, какие опции?

**Comment by duxabilii** [comment]
Можно, как вариант включить дебаг и тогда каждый раз кеш будет перезаписываться
```
$templator = new Templator($cachePath);
$templator->debug = true;
```

**Comment by vkatochka** [comment]
Я так и поступил, но все же это debug ).
Отличный вариант, когда скрипт запоминает на дату последнего изменения шаблона, и при её изменении, перезаписывает кеш.

**Comment by shadz3rg** [comment]
@vkatochka Да в общем debug режим только ради этого и был придуман, можно смело юзать.

> Отличный вариант, когда скрипт запоминает на дату последнего изменения шаблона, и при её изменении, перезаписывает кеш.  

Как я это вижу - можно сохранять хэш исходного файла комментарием в шаблоне и сверяться с ним. 
Займусь как будет свободное время.

**Comment by shadz3rg** [comment]
Готово в 0.2.0
Опция trackDocument, по умолчанию отключена.
